// W5-2a: finish the last legacy db.ts memory/kanban call-sites that W4 missed.
//  - routes/migrate.ts  saveAgentMemory  db.ts -> noa-memory  (real noa.db here)
//  - routes/ideas.ts    createKanbanCard -> noa-kanban.createCard  (mock-asserted)
// These were the only two live callers of legacy db.ts memory/kanban code after
// W1-W4 + W5-1; migrating them makes the db.ts legacy code fully dead for the
// W5-2b strip. The migrate test also proves the legacy 5-arg call
// saveAgentMemory(..., autoGenerated=true) is accepted on the SLIM schema (the
// auto_generated column is gone -> noa-memory must swallow the arg, not crash).
import { describe, it, expect, beforeAll, beforeEach, afterAll, vi } from 'vitest'
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { tmpdir } from 'node:os'
import { fileURLToPath } from 'node:url'
import { Readable } from 'node:stream'

// ---- migrate.ts: REAL noa.db integration (no mocks) ----
import { initNoaDb, getNoaDb } from '../noa-memory.js'
import { tryHandleMigrate } from '../web/routes/migrate.js'
import { MAIN_AGENT_ID } from '../config.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const SCHEMA_SQL = readFileSync(join(__dirname, '..', '..', 'scripts', 'schema-noa.sql'), 'utf8')

function call(handler: (ctx: any) => Promise<boolean>, method: string, fullPath: string, body?: unknown) {
  const url = new URL('http://x' + fullPath)
  const req = Readable.from(body === undefined ? [] : [Buffer.from(JSON.stringify(body))]) as any
  const captured: { status: number; body: any } = { status: 200, body: undefined }
  const res = {
    writeHead(s: number) { captured.status = s; return res },
    end(b?: string) { captured.body = b ? JSON.parse(b) : undefined },
  } as any
  return handler({ req, res, method, path: url.pathname, url }).then((handled: boolean) => ({ handled, ...captured }))
}

describe('W5-2a migrate.ts -> noa-memory (real noa.db)', () => {
  let fixtureDir: string
  beforeAll(() => {
    process.env.NODE_ENV = 'test'
    initNoaDb(':memory:')
    getNoaDb().exec(SCHEMA_SQL)
    fixtureDir = mkdtempSync(join(tmpdir(), 'w52a-mig-'))
  })
  afterAll(() => { try { rmSync(fixtureDir, { recursive: true, force: true }) } catch {} })
  beforeEach(() => { getNoaDb().prepare('DELETE FROM memories').run() })

  it('imports a personality finding into noa.db (legacy 5-arg call, slim schema OK)', async () => {
    const f = join(fixtureDir, 'soul.md')
    writeFileSync(f, 'A NoA asszisztens szemelyisege: nyugodt, kimert, megbizhato.')
    const r = await call(tryHandleMigrate, 'POST', '/api/migrate/run', {
      agentId: 'dave',
      findings: [{ type: 'personality', path: f, name: 'soul.md' }],
    })
    expect(r.handled).toBe(true)
    expect(r.body.imported).toBeGreaterThanOrEqual(1)
    const row = getNoaDb()
      .prepare("SELECT agent_id, content, category FROM memories WHERE agent_id = ? ORDER BY id DESC LIMIT 1")
      .get('dave') as { agent_id: string; content: string; category: string } | undefined
    expect(row).toBeTruthy()
    expect(row!.content).toContain('Importált személyiség')
    expect(row!.category).toBe('warm')
  })
})

// ---- ideas.ts: mock db.js (idea_box reads) + mock noa-kanban (createCard) ----
vi.mock('../db.js', () => {
  const idea = { id: 'idea1', title: 'Teszt otlet', description: 'leiras', status: 'new' }
  return {
    listIdeas: vi.fn(), createIdea: vi.fn(), updateIdea: vi.fn(() => true),
    deleteIdea: vi.fn(), listIdeaCategories: vi.fn(),
    getDb: vi.fn(() => ({ prepare: () => ({ get: () => idea, run: () => ({ changes: 1 }) }) })),
  }
})
vi.mock('../noa-kanban.js', () => ({ createCard: vi.fn(() => ({ id: 'card1' })) }))

import { tryHandleIdeas } from '../web/routes/ideas.js'
import { createCard } from '../noa-kanban.js'

describe('W5-2a ideas.ts promote -> noa-kanban.createCard', () => {
  beforeEach(() => { vi.clearAllMocks() })

  it('promote creates the kanban card via noa-kanban (not legacy db.ts)', async () => {
    const r = await call(tryHandleIdeas, 'POST', '/api/ideas/idea1/promote', { phase: 'plan' })
    expect(r.handled).toBe(true)
    expect(createCard).toHaveBeenCalledTimes(1)
    const arg = (createCard as any).mock.calls[0][0]
    expect(arg.title).toBe('Teszt otlet')
    expect(arg.status).toBe('planned')
    expect(arg.project).toBe('ENG') // canonical taxonomy (card cf0d1bfe); promoted ideas default to ENG
  })
})
