// C12 chameleon canary harness (kanban 6d8b5f70).
//
// One persistent sandbox agent ("buster") that normally just exists at
// baseline and serves as a launcher/config/monitor canary: it dies first if
// the launch path breaks, warning us before a live agent dies, and keeps the
// keep-alive / MCP pipe warm.
//
// To validate a change to an agent we:
//   1. morph(target)  -- rebuild the sandbox as a disposable clone of `target`
//   2. smoke(...)      -- launch, survive a window, answer an inter-agent ping
//   3. promote(target) -- copy the validated files into the LIVE target
//   4. revert()        -- clean rebuild of the sandbox back to baseline
//
// Hard constraints (from the C12 spec):
//   - DISTINCT session name (`agent-buster`), never a shared name -- guaranteed
//     by deriving the session from the sandbox agent name.
//   - PID-only kills (never `pkill -f`): we reuse stopAgentProcess, which kills
//     the named tmux session and reaps orphans by explicit PID (see
//     channel-poller-reap.ts). No process is matched by command-line substring.
//   - NEVER the real channel token: morph copies config but no channels/ token,
//     and forces channel-less + shared auth so the clone cannot 409 against the
//     original or spend on its API key.
//   - Clean attribution: the morphed CLAUDE.md carries a banner telling the
//     clone to identify itself as "buster" in all mail/cost, never as `target`.
//   - "revert to baseline" is a CLEAN REBUILD (destroy + recreate from the
//     baseline snapshot), NOT an in-place undo, so residue from a previous
//     morph (memory, sessions, .claude.json projects, tokens) cannot bleed into
//     the next test and make it lie.
//
// Architecture mirrors the rest of src/web: pure decision/transform functions
// (exported, unit-tested with no fs/tmux) and thin IO wrappers around them.

import {
  existsSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  rmSync,
  cpSync,
  copyFileSync,
  readdirSync,
} from 'node:fs'
import { join } from 'node:path'
import { logger } from '../logger.js'
import { MAIN_AGENT_ID } from '../config.js'
import { agentDir, isKnownAgent, readFileOr } from './agent-config.js'
import { scaffoldAgentDir } from './agent-scaffold.js'
import { ensureAgentConfigDir, CHANNEL_PLUGIN_IDS } from './agent-config-dir.js'
import {
  agentSessionName,
  isAgentRunning,
  startAgentProcess,
  stopAgentProcess,
  sendPromptToSession,
} from './agent-process.js'
import { createAgentMessage, listAgentMessages } from '../db.js'

// The persistent sandbox agent. Its tmux session is `agent-buster` (distinct
// from every live agent), satisfying the "distinct session name" hard
// constraint by construction.
export const SANDBOX_AGENT = 'buster'

// Identity files snapshotted into .baseline and restored on every clean
// rebuild. Everything else under the sandbox dir is regenerated by
// scaffoldAgentDir / ensureAgentConfigDir, so it never needs snapshotting.
export const BASELINE_FILES = ['CLAUDE.md', 'SOUL.md', 'agent-config.json', '.mcp.json'] as const
const BASELINE_DIRNAME = '.baseline'

// Entries under the sandbox dir that a clean rebuild must NEVER delete.
const RESET_PROTECTED = new Set([BASELINE_DIRNAME, '.git'])

// Banner delimiters so promote() can strip the banner back off byte-exactly
// when copying CLAUDE.md to the live target.
export const BANNER_START = '<!-- C12-SANDBOX-BANNER:START -->'
export const BANNER_END = '<!-- C12-SANDBOX-BANNER:END -->'

// Files/dirs promote() copies from the sandbox to the live target BY DEFAULT.
// This is the SAFE default surface: behaviour + identity only. It deliberately
// excludes agent-config.json, settings.json, .mcp.json and anything under
// channels/ -- the default must never be able to leak a token or a path. The
// riskier surfaces are explicit opt-in (see PromoteOptions.include*).
export const PROMOTABLE_FILES = ['CLAUDE.md', 'SOUL.md'] as const
export const PROMOTABLE_DIRS = [join('.claude', 'skills')] as const

// The ONLY agent-config.json fields promote() may carry from the sandbox to the
// live target, and only under the --with-config opt-in. model + securityProfile
// are the legitimate right-sizing promote case; displayName is cosmetic-safe.
// channelProvider, claudeConfigDir, authMode and any token-bearing field are
// NEVER promoted -- they would repoint the live agent's channel or leak a
// path/credential. The merge keeps the target's existing config as the base and
// overlays only these whitelisted keys.
export const PROMOTABLE_CONFIG_FIELDS = ['model', 'securityProfile', 'displayName'] as const

// Smoke-test defaults.
export const DEFAULT_SURVIVE_MS = 60 * 1000
export const DEFAULT_POLL_MS = 5 * 1000
export const DEFAULT_PING_TIMEOUT_MS = 60 * 1000

// ---------------------------------------------------------------------------
// Pure functions (no fs/tmux/db) -- unit-tested in isolation.
// ---------------------------------------------------------------------------

export type SmokeVerdict = 'pass' | 'fail-died' | 'fail-no-ping'

// Pure verdict from the two observed smoke-test facts. Liveness gates first:
// an agent that died is fail-died regardless of any (impossible) ping reply.
export function decideSmokeVerdict(survived: boolean, pingAnswered: boolean): SmokeVerdict {
  if (!survived) return 'fail-died'
  if (!pingAnswered) return 'fail-no-ping'
  return 'pass'
}

// The sandbox tmux session name. Hardcoded constant cross-checked in tests
// against agentSessionName(SANDBOX_AGENT) so the distinct-session guarantee is
// pinned even if the session naming scheme changes.
export function sandboxSessionName(): string {
  return `agent-${SANDBOX_AGENT}`
}

// True for entries a clean rebuild must preserve.
export function isProtectedFromReset(entry: string): boolean {
  return RESET_PROTECTED.has(entry)
}

// Transform the target's agent-config.json into the sandbox's config. Keeps
// only the launch-relevant fields (model, securityProfile); forces the clone
// channel-less and onto shared auth so it can never hold the target's real
// channel token or API key; records what it is a clone of for attribution.
export function sanitizeMorphedConfig(rawConfigJson: string, target: string): Record<string, unknown> {
  let parsed: Record<string, unknown> = {}
  try {
    const p = JSON.parse(rawConfigJson)
    if (p && typeof p === 'object' && !Array.isArray(p)) parsed = p as Record<string, unknown>
  } catch { /* fall through to defaults */ }

  const out: Record<string, unknown> = {}
  if (typeof parsed.model === 'string') out.model = parsed.model
  if (typeof parsed.securityProfile === 'string') out.securityProfile = parsed.securityProfile
  // Channel-less + shared auth are non-negotiable for the sandbox: never the
  // real token (409 hazard), never the target's metered API key.
  out.channelProvider = null
  out.authMode = 'shared'
  out.sandboxCloneOf = target
  return out
}

// Banner prepended to the cloned CLAUDE.md so the running clone knows it is a
// throwaway and attributes itself as "buster", never as the target.
export function sandboxBannerFor(target: string): string {
  return [
    BANNER_START,
    '> SANDBOX NOTICE (C12 chameleon canary)',
    '>',
    `> You are running inside the BUSTER sandbox as a DISPOSABLE clone of "${target}".`,
    '> This instance will be destroyed and rebuilt; nothing you do here is permanent.',
    `> In EVERY inter-agent message identify yourself as "buster", NEVER as "${target}".`,
    '> Do NOT send channel (Telegram/Slack/Discord) messages and do NOT use the real',
    "> agent's credentials. Attribute all cost and mail to \"buster\" so the sandbox is",
    '> never conflated with the original.',
    BANNER_END,
    '',
    '',
  ].join('\n')
}

// Remove a leading sandbox banner (between BANNER_START and BANNER_END plus the
// trailing blank lines) so promote() writes the target a banner-free CLAUDE.md.
// Returns the input unchanged when no banner is present.
export function stripSandboxBanner(claudeMd: string): string {
  const start = claudeMd.indexOf(BANNER_START)
  if (start !== 0) return claudeMd
  const endMarker = claudeMd.indexOf(BANNER_END)
  if (endMarker === -1) return claudeMd
  let rest = claudeMd.slice(endMarker + BANNER_END.length)
  rest = rest.replace(/^\r?\n(\r?\n)?/, '')
  return rest
}

// Merge ONLY the whitelisted fields (PROMOTABLE_CONFIG_FIELDS) from the
// sandbox's agent-config into the target's, keeping the target's config as the
// base. This guarantees the live agent's channelProvider, claudeConfigDir,
// authMode and any token field are preserved verbatim and can never be
// overwritten or leaked from the sandbox clone. Pure; no fs.
export function sanitizePromotedConfig(sandboxConfigJson: string, targetConfigJson: string): Record<string, unknown> {
  let base: Record<string, unknown> = {}
  try {
    const t = JSON.parse(targetConfigJson)
    if (t && typeof t === 'object' && !Array.isArray(t)) base = t as Record<string, unknown>
  } catch { /* target unreadable -> start from empty, still no sandbox leakage */ }

  let sandbox: Record<string, unknown> = {}
  try {
    const s = JSON.parse(sandboxConfigJson)
    if (s && typeof s === 'object' && !Array.isArray(s)) sandbox = s as Record<string, unknown>
  } catch { /* nothing to overlay */ }

  for (const f of PROMOTABLE_CONFIG_FIELDS) {
    if (typeof sandbox[f] === 'string') base[f] = sandbox[f]
  }
  return base
}

// Strip the channel-plugin keys (CHANNEL_PLUGIN_IDS) out of a settings.json's
// enabledPlugins so promoting settings under --with-settings carries
// permissions / hooks / effortLevel but never flips the target's channel state.
// Drops the enabledPlugins map entirely if stripping empties it. Pure; no fs.
export function stripChannelKeysFromSettings(rawJson: string): Record<string, unknown> {
  let parsed: Record<string, unknown> = {}
  try {
    const p = JSON.parse(rawJson)
    if (p && typeof p === 'object' && !Array.isArray(p)) parsed = p as Record<string, unknown>
  } catch { /* return empty */ }

  const ep = parsed.enabledPlugins
  if (ep && typeof ep === 'object' && !Array.isArray(ep)) {
    const map = ep as Record<string, unknown>
    for (const id of CHANNEL_PLUGIN_IDS) delete map[id]
    if (Object.keys(map).length === 0) delete parsed.enabledPlugins
  }
  return parsed
}

// Guard for --with-mcp promotion. morph copies the TARGET's .mcp.json into the
// sandbox, so promoting it back verbatim is normally an identity round-trip --
// BUT if the file was edited during testing (or ever carried an absolute path
// into the sandbox dir), a Buster-only path/entry must never bleed back into
// the live agent. Returns true if the raw JSON text references the sandbox
// agent dir in any form. Pure; text-level so it catches paths regardless of
// where in the structure they sit.
export function mcpJsonReferencesSandbox(rawJson: string): boolean {
  return (
    rawJson.includes(`agents/${SANDBOX_AGENT}`) ||
    rawJson.includes(`/${SANDBOX_AGENT}/.claude`) ||
    rawJson.includes('sandboxCloneOf')
  )
}

// The direct prompt injected into the sandbox to elicit an inter-agent reply.
// Sent straight to the pane (not via the untrusted router), so the clone sees
// it as a normal operator prompt and is free to act on it.
export function pingPromptFor(nonce: string): string {
  return (
    `[C12 smoke test] Reply immediately by sending ONE inter-agent message from "buster" ` +
    `to "c12-harness" whose content is EXACTLY: PONG ${nonce}. ` +
    `Use the dashboard messages API (POST /api/messages). Do nothing else.`
  )
}

// ---------------------------------------------------------------------------
// IO: baseline snapshot + clean rebuild
// ---------------------------------------------------------------------------

function copyIfExists(src: string, dest: string): void {
  if (existsSync(src)) copyFileSync(src, dest)
}

// Capture the sandbox's current identity files into .baseline the first time.
// Idempotent: once the snapshot exists it is the source of truth for reverts
// and is never re-captured (so a morph can never poison the baseline).
export function ensureSandboxBaseline(): void {
  const dir = agentDir(SANDBOX_AGENT)
  const baseline = join(dir, BASELINE_DIRNAME)
  if (existsSync(baseline)) return
  mkdirSync(baseline, { recursive: true })
  for (const f of BASELINE_FILES) copyIfExists(join(dir, f), join(baseline, f))
  logger.info({ baseline }, 'chameleon: captured sandbox baseline snapshot')
}

export interface OpResult {
  ok: boolean
  error?: string
}

// Clean rebuild: stop (PID/session-scoped), destroy every live entry except the
// protected baseline, restore identity files from the baseline, then recreate
// the empty .claude tree + isolated config dir from scratch. This is a
// destroy-and-recreate, never an in-place undo.
export function revertSandboxToBaseline(): OpResult {
  const dir = agentDir(SANDBOX_AGENT)
  if (!existsSync(dir)) return { ok: false, error: 'sandbox agent dir not found' }
  ensureSandboxBaseline()

  // PID/session-scoped stop only -- stopAgentProcess kills the `agent-buster`
  // tmux session and reaps orphans by explicit PID; no `pkill -f` anywhere.
  if (isAgentRunning(SANDBOX_AGENT)) stopAgentProcess(SANDBOX_AGENT)

  for (const entry of readdirSync(dir)) {
    if (isProtectedFromReset(entry)) continue
    try {
      rmSync(join(dir, entry), { recursive: true, force: true })
    } catch (err) {
      logger.warn({ err, entry }, 'chameleon: failed to remove sandbox entry during rebuild')
    }
  }

  const baseline = join(dir, BASELINE_DIRNAME)
  for (const f of BASELINE_FILES) copyIfExists(join(baseline, f), join(dir, f))

  scaffoldAgentDir(SANDBOX_AGENT)
  ensureAgentConfigDir(SANDBOX_AGENT)
  logger.info('chameleon: sandbox reverted to baseline (clean rebuild)')
  return { ok: true }
}

export interface MorphResult extends OpResult {
  target?: string
}

// Rebuild the sandbox as a disposable clone of `target`. Always starts from a
// clean baseline so no residue from a previous morph survives.
export function morphSandbox(target: string): MorphResult {
  if (target === SANDBOX_AGENT) return { ok: false, error: 'cannot morph the sandbox into itself' }
  if (target === MAIN_AGENT_ID) return { ok: false, error: 'refusing to morph into the main agent' }
  if (!isKnownAgent(target)) return { ok: false, error: `unknown target agent: ${target}` }

  const targetDir = agentDir(target)
  const dir = agentDir(SANDBOX_AGENT)

  const rev = revertSandboxToBaseline()
  if (!rev.ok) return { ok: false, error: `revert before morph failed: ${rev.error}` }

  // CLAUDE.md with the sandbox banner prepended.
  const claudeSrc = join(targetDir, 'CLAUDE.md')
  if (existsSync(claudeSrc)) {
    const body = readFileSync(claudeSrc, 'utf-8')
    writeFileSync(join(dir, 'CLAUDE.md'), sandboxBannerFor(target) + body)
  }
  // SOUL.md and .mcp.json verbatim (the latter keeps the MCP pipe warm).
  copyIfExists(join(targetDir, 'SOUL.md'), join(dir, 'SOUL.md'))
  copyIfExists(join(targetDir, '.mcp.json'), join(dir, '.mcp.json'))

  // Sanitized agent-config.json: model + profile only, channel-less, shared
  // auth, attribution marker. NEVER the target's channel token.
  const cfg = sanitizeMorphedConfig(readFileOr(join(targetDir, 'agent-config.json'), '{}'), target)
  writeFileSync(join(dir, 'agent-config.json'), JSON.stringify(cfg, null, 2) + '\n')

  // The agent's learned skills (its earned behaviour under test).
  const skillsSrc = join(targetDir, '.claude', 'skills')
  if (existsSync(skillsSrc)) {
    cpSync(skillsSrc, join(dir, '.claude', 'skills'), { recursive: true })
  }

  // Rebuild the isolated config dir against the morphed identity.
  ensureAgentConfigDir(SANDBOX_AGENT)
  logger.info({ target }, 'chameleon: sandbox morphed into target clone')
  return { ok: true, target }
}

// ---------------------------------------------------------------------------
// IO: smoke test (launch -> survive -> answer ping)
// ---------------------------------------------------------------------------

export interface SmokeOptions {
  surviveMs?: number
  pollMs?: number
  pingTimeoutMs?: number
  // Leave the sandbox running after the test instead of stopping it.
  keepRunning?: boolean
  // Injectable seams for deterministic tests.
  now?: () => number
  sleep?: (ms: number) => Promise<void>
  waitForPingReply?: (afterId: number, nonce: string, timeoutMs: number) => Promise<boolean>
}

export interface SmokeResult {
  verdict: SmokeVerdict
  survived: boolean
  pingAnswered: boolean
  details: string
}

function latestMessageId(): number {
  const msgs = listAgentMessages(1)
  return msgs.length > 0 ? msgs[0]!.id : 0
}

// Default ping-reply detector: poll the agent_messages table for any message
// created after the ping whose content carries the unique nonce. The nonce is
// unique per run, so matching on content alone is unambiguous regardless of
// whether the clone replies as "buster" or under the morphed name.
async function defaultWaitForPingReply(afterId: number, nonce: string, timeoutMs: number): Promise<boolean> {
  const deadline = Date.now() + timeoutMs
  while (Date.now() < deadline) {
    const msgs = listAgentMessages(50)
    if (msgs.some(m => m.id > afterId && m.content.includes(nonce))) return true
    await new Promise(r => setTimeout(r, 2000))
  }
  return false
}

// Run the canary smoke test on the (already morphed or baseline) sandbox:
// launch it, confirm it survives the window, then confirm it answers an
// inter-agent ping. Always stops the sandbox at the end unless keepRunning.
export async function smokeTestSandbox(opts: SmokeOptions = {}): Promise<SmokeResult> {
  const surviveMs = opts.surviveMs ?? DEFAULT_SURVIVE_MS
  const pollMs = opts.pollMs ?? DEFAULT_POLL_MS
  const pingTimeoutMs = opts.pingTimeoutMs ?? DEFAULT_PING_TIMEOUT_MS
  const now = opts.now ?? (() => Date.now())
  const sleep = opts.sleep ?? ((ms: number) => new Promise<void>(r => setTimeout(r, ms)))
  const waitForReply = opts.waitForPingReply ?? defaultWaitForPingReply

  const start = startAgentProcess(SANDBOX_AGENT)
  if (!start.ok) {
    return { verdict: 'fail-died', survived: false, pingAnswered: false, details: `launch failed: ${start.error}` }
  }

  // Liveness: poll for the survival window. A canary that dies here is exactly
  // the early warning the sandbox exists to give.
  const deadline = now() + surviveMs
  let survived = true
  while (now() < deadline) {
    await sleep(pollMs)
    if (!isAgentRunning(SANDBOX_AGENT)) { survived = false; break }
  }
  if (!survived) {
    if (!opts.keepRunning && isAgentRunning(SANDBOX_AGENT)) stopAgentProcess(SANDBOX_AGENT)
    return { verdict: 'fail-died', survived: false, pingAnswered: false, details: 'sandbox died within the survival window' }
  }

  // Ping: inject a prompt eliciting an inter-agent reply carrying a nonce.
  const nonce = `C12-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`
  const lastIdBeforePing = latestMessageId()
  sendPromptToSession(sandboxSessionName(), pingPromptFor(nonce))
  const pingAnswered = await waitForReply(lastIdBeforePing, nonce, pingTimeoutMs)

  if (!opts.keepRunning) stopAgentProcess(SANDBOX_AGENT)

  const verdict = decideSmokeVerdict(survived, pingAnswered)
  return {
    verdict,
    survived,
    pingAnswered,
    details: verdict === 'pass'
      ? 'sandbox launched, survived the window, and answered the ping'
      : 'sandbox survived but did not answer the ping within the timeout',
  }
}

// ---------------------------------------------------------------------------
// IO: promote validated files to the LIVE target
// ---------------------------------------------------------------------------

export interface PromoteOptions {
  files?: readonly string[]
  dirs?: readonly string[]
  // Opt-in extensions to the safe default surface. Each is field-filtered so it
  // cannot leak a token or path (see the pure helpers above).
  //   includeAgentConfig -> agent-config.json, model/securityProfile/displayName only
  //   includeSettings    -> .claude/settings.json with channel keys stripped
  //   includeMcp         -> .mcp.json verbatim (when the MCP config is the change)
  includeAgentConfig?: boolean
  includeSettings?: boolean
  includeMcp?: boolean
  // Required: promotion writes to a LIVE agent and is hard to reverse.
  confirm?: boolean
}

export interface PromoteResult extends OpResult {
  promoted: string[]
  backupDir?: string
}

// Copy validated files from the sandbox into the live target. Backs the
// target's current copies up first (reversible), strips the sandbox banner off
// CLAUDE.md, and refuses to touch channel state or agent-config.json. Requires
// an explicit confirm because it mutates a live agent.
export function promoteToLive(target: string, opts: PromoteOptions = {}): PromoteResult {
  if (target === SANDBOX_AGENT) return { ok: false, error: 'cannot promote to the sandbox', promoted: [] }
  if (target === MAIN_AGENT_ID) return { ok: false, error: 'refusing to promote to the main agent', promoted: [] }
  if (!isKnownAgent(target)) return { ok: false, error: `unknown target agent: ${target}`, promoted: [] }
  if (!opts.confirm) return { ok: false, error: 'promotion requires explicit confirm (writes to a live agent)', promoted: [] }

  const sandboxDir = agentDir(SANDBOX_AGENT)
  const targetDir = agentDir(target)
  const files = opts.files ?? PROMOTABLE_FILES
  const dirs = opts.dirs ?? PROMOTABLE_DIRS

  // Fail-fast BEFORE any write: refuse a --with-mcp promotion whose .mcp.json
  // carries a sandbox-specific path / Buster-only entry, so no Buster byproduct
  // can bleed back into the live agent. Checked up front so a leak aborts the
  // whole promote without having partially written other files.
  if (opts.includeMcp) {
    const mcpSrc = join(sandboxDir, '.mcp.json')
    if (existsSync(mcpSrc) && mcpJsonReferencesSandbox(readFileSync(mcpSrc, 'utf-8'))) {
      return { ok: false, error: 'refusing to promote: .mcp.json references the sandbox (would leak a Buster-only path/entry)', promoted: [] }
    }
  }

  const backupDir = join(targetDir, `.c12-backup-${Date.now()}`)
  mkdirSync(backupDir, { recursive: true })
  const promoted: string[] = []

  for (const rel of files) {
    const src = join(sandboxDir, rel)
    if (!existsSync(src)) continue
    const dest = join(targetDir, rel)
    if (existsSync(dest)) copyFileSync(dest, join(backupDir, rel.replace(/[\\/]/g, '_')))
    let content = readFileSync(src, 'utf-8')
    if (rel === 'CLAUDE.md') content = stripSandboxBanner(content)
    mkdirSync(join(dest, '..'), { recursive: true })
    writeFileSync(dest, content)
    promoted.push(rel)
  }

  for (const rel of dirs) {
    const src = join(sandboxDir, rel)
    if (!existsSync(src)) continue
    const dest = join(targetDir, rel)
    if (existsSync(dest)) {
      cpSync(dest, join(backupDir, rel.replace(/[\\/]/g, '_')), { recursive: true })
      rmSync(dest, { recursive: true, force: true })
    }
    cpSync(src, dest, { recursive: true })
    promoted.push(rel)
  }

  // Opt-in: agent-config.json, whitelisted fields only (never channel/path).
  if (opts.includeAgentConfig) {
    const rel = 'agent-config.json'
    const src = join(sandboxDir, rel)
    if (existsSync(src)) {
      const dest = join(targetDir, rel)
      const targetRaw = existsSync(dest) ? readFileSync(dest, 'utf-8') : '{}'
      if (existsSync(dest)) copyFileSync(dest, join(backupDir, rel))
      const merged = sanitizePromotedConfig(readFileSync(src, 'utf-8'), targetRaw)
      writeFileSync(dest, JSON.stringify(merged, null, 2) + '\n')
      promoted.push(`${rel} (${PROMOTABLE_CONFIG_FIELDS.join('/')} only)`)
    }
  }

  // Opt-in: settings.json with channel-plugin keys stripped.
  if (opts.includeSettings) {
    const rel = join('.claude', 'settings.json')
    const src = join(sandboxDir, rel)
    if (existsSync(src)) {
      const dest = join(targetDir, rel)
      if (existsSync(dest)) copyFileSync(dest, join(backupDir, rel.replace(/[\\/]/g, '_')))
      const stripped = stripChannelKeysFromSettings(readFileSync(src, 'utf-8'))
      mkdirSync(join(dest, '..'), { recursive: true })
      writeFileSync(dest, JSON.stringify(stripped, null, 2) + '\n')
      promoted.push(`${rel} (channel keys stripped)`)
    }
  }

  // Opt-in: .mcp.json verbatim (only when the MCP config is the change).
  if (opts.includeMcp) {
    const rel = '.mcp.json'
    const src = join(sandboxDir, rel)
    if (existsSync(src)) {
      const dest = join(targetDir, rel)
      if (existsSync(dest)) copyFileSync(dest, join(backupDir, rel))
      copyFileSync(src, dest)
      promoted.push(rel)
    }
  }

  logger.info({ target, promoted, backupDir }, 'chameleon: promoted validated files to live target')
  return { ok: true, promoted, backupDir }
}
